### ISSUE TITLE
Issues with email

### ISSUE THREAD

**Issue by Gunpowderchant** [mikulash/Octoprint-detector2#19]
Hi, I'm not sure I'm doing something wrong, I installed the plugin, made an outlook account and made sure the email settings are as shown on the documentation, but when the alert rings, I can hear the alarm on the browser but instead of getting and email I get this popup indicating

"Mail: Only elasticemail is supported as an SMTP host. To open an account please visit..." and then a link to their website.

what am I doing wrong?

**Comment by WorldSealer** [comment]
Hello, I was having the same trouble, the only link I could find on it was this one: https://stackoverflow.com/questions/72209946/how-to-solve-the-smtpjs-error-with-gmail-smtp-host. I am hoping that there is a better solution to this problem though.

**Comment by mikulash** [comment]
Hey, I noticed it recently as well. All over their website was written that you can use any SMTP server and now the want you to use theirs paid one. Working on alternative way of sending though. Might be out soon, maybe even today.

**Comment by mikulash** [comment]
God damn that took long. But finally I found time to do it so the fix should be available to download in couple of hours via plugin manager.
