### ISSUE TITLE
I just did a fresh new install but does not show up in plugin manager

### ISSUE THREAD

**Issue by barnes-dev** [mikulash/Octoprint-detector2#21]
I just did a fresh install.  I am running under docker,  The Timelapse works and it shows up under installed plugins, and is enabled, but I cannot configure it under Plugins.  I am using UI Customizer.  Tried to disable it but no luck
[octoprint-systeminfo-20220827173606.zip](https://github.com/mikulash/Octoprint-detector2/files/9438423/octoprint-systeminfo-20220827173606.zip)
.

**Comment by barnes-dev** [comment]
I uninstalled octoprint ui customizer plug-in.  Then I was able to do the install of defender 2.  After that I  reinstalled ui customizer and everything is fine

**Comment by mikulash** [comment]
did this happen just to this plugin or to some others as well?

**Comment by barnes-dev** [comment]
Not sure. It was the only plug-in I tried to install that would not work
until I deinstalled the customize ui.
